name = "GongJaWal-Theme"
description = "Simple Hugo documentation theme zdoc modified for GongJaWal."
homepage = "https://github.com/gongjawal/gongjawal-theme"
license = "MIT"
licenselink = "https://github.com/gongjawal/gongjawal-theme"
tags = ["accessible", "multilingual", "responsive", "documentation", "search", "simple", "light", "dark", "mobile"]
features = ["accessible", "multilingual", "responsive", "grid", "sass", "search", "fast"]
min_version = "0.65.0"

[author]
  name = "junukwon7"
  homepage = "https://github.com/gongjawal/gongjawal-theme"
